spring:
   application:
      name: file-service
server:
   port: 8080

---
spring:
   profiles: dev
   application:
      name: file-service
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: file-service
server: 
   port: 4431